export const GET_REWARD_INFO = 'GET_REWARD_INFO';
export const REWARD_SUCCESS = 'REWARD_SUCCESS';
export const REWARD_FAILURE = 'REWARD_FAILURE';

export const GET_REWARD_COUPON = 'GET_REWARD_COUPON';
export const GET_REWARD_COUPON_SUCCESS = 'GET_REWARD_COUPON_SUCCESS';
export const GET_REWARD_COUPON_FAILURE = 'GET_REWARD_COUPON_FAILURE';

export const REDEEM_REWARDS = 'REDEEM_REWARDS';