export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const GET_NETWORK_LIST = 'GET_NETWORK_LIST';
export const SET_NETWORK_LIST = 'SET_NETWORK_LIST';
export const GET_TAGGED_NETWORK = 'GET_TAGGED_NETWORK';
export const SET_TAGGED_NETWORK = 'SET_TAGGED_NETWORK';
export const TAG_NETWORK = 'TAG_NETWORK';

export const REDEEM_POINTS = 'REDEEM_POINTS';

export const UPLOAD_KYC = 'UPLOAD_KYC';
export const GET_KYC_DETAILS = 'GET_KYC_DETAILS';
export const SET_KYC_DETAILS = 'SET_KYC_DETAILS';

export const GET_BANK_LIST = 'GET_BANK_LIST';
export const SET_BANK_LIST = 'SET_BANK_LIST';

export const ADD_BANK_ACCOUNT = 'ADD_BANK_ACCOUNT';
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const SET_BANK_DETAILS = 'SET_BANK_DETAILS';

export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT';

export const GET_ALL_TRANSACTION = 'GET_ALL_TRANSACTION';
export const SET_ALL_TRANSACTION = 'SET_ALL_TRANSACTION';